import{a as v,S,i as c}from"./assets/vendor-5YrzWRhu.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const u of r.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&d(u)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const q="51405205-50fb9ad3708ee85f3446db19a",E="https://pixabay.com/api/",R=15;async function p(s,t){const o={key:q,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:R};return(await v.get(E,{params:o})).data}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more"),B=new S(".gallery a");function g(s){const t=s.map(o=>`
    <a href="${o.largeImageURL}" class="gallery-item">
      <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy"/>
      <div class="info">
        <p><b>Likes</b> ${o.likes}</p>
        <p><b>Views</b> ${o.views}</p>
        <p><b>Comments</b> ${o.comments}</p>
        <p><b>Downloads</b> ${o.downloads}</p>
      </div>
    </a>
  `).join("");m.insertAdjacentHTML("beforeend",t),B.refresh()}function $(){m.innerHTML=""}function L(){h.classList.remove("hidden")}function i(){h.classList.add("hidden")}function b(){y.classList.remove("hidden")}function l(){y.classList.add("hidden")}const w=document.querySelector(".search-form"),M=w.querySelector('input[name="searchQuery"]'),P=document.querySelector(".load-more");let a="",n=1,f=0;w.addEventListener("submit",async s=>{if(s.preventDefault(),a=M.value.trim(),!!a){n=1,$(),l(),L();try{const t=await p(a,n);if(f=t.totalHits,t.hits.length===0){c.info({message:"No images found.",position:"topRight"}),i();return}g(t.hits),i(),f>n*15?b():l()}catch{c.error({message:"Error fetching images",position:"topRight"}),i()}}});P.addEventListener("click",async()=>{n++,L(),l();try{const s=await p(a,n);g(s.hits),i();const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"}),n*15>=f?(l(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b()}catch{c.error({message:"Error loading more images",position:"topRight"}),i()}});
//# sourceMappingURL=index.js.map
