import{a as S,S as q,i as s}from"./assets/vendor-LK6CqzKq.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const d of t.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const b="51317900-f0372c6e5a84e0989a980511e",v="https://pixabay.com/api/";async function p(r,o=1){try{const a={key:b,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o};return(await S.get(v,{params:a})).data}catch{throw new Error("Failed to fetch images")}}const u=document.querySelector(".gallery"),h=document.querySelector(".loader"),g=document.querySelector(".load-more");let R=new q(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const o=r.map(e=>`
          <li class="gallery-item">
          <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
          </a>
          <div class="info">
          <p>👍 ${e.likes}</p>
          <p>👁️ ${e.views}</p>
          <p>💬 ${e.comments}</p>
          <p>⬇️ ${e.downloads}</p>
          </div>
          </li>
          `).join("");u.insertAdjacentHTML("beforeend",o);const a=u.querySelectorAll("img"),n=Array.from(a).map(e=>new Promise(t=>{e.complete?t():(e.onload=()=>t(),e.onerror=()=>t())}));Promise.all(n).then(()=>{R.refresh(),f()})}function I(){u.innerHTML=""}function L(){h.classList.remove("hidden")}function f(){h.classList.add("hidden")}function w(){g.classList.remove("hidden")}function l(){g.classList.add("hidden")}const A=document.querySelector(".form"),B=document.querySelector(".load-more");document.querySelector(".gallery");let i="",c=1,m=0;A.addEventListener("submit",async r=>{if(r.preventDefault(),i=r.target.elements["search-text"].value.trim(),c=1,I(),l(),!i){s.warning({message:"Please enter a search term!",position:"topRight"});return}L();try{const o=await p(i,c);if(m=o.totalHits,o.hits.length===0){s.error({message:"No images found. Try a different query.",position:"topRight"});return}y(o.hits),document.querySelectorAll(".gallery-item").length<m?w():(l(),s.info({message:"You've reached the end of the search results.",position:"topRight"}))}catch{s.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{f()}});B.addEventListener("click",async()=>{c+=1,l(),L();try{const r=await p(i,c);y(r.hits);const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),document.querySelectorAll(".gallery-item").length<m?w():(l(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{s.error({message:"Failed to load more images.",position:"topRight"})}finally{f()}});
//# sourceMappingURL=index.js.map
